name: Digger Pull Request Workflow

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize ]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  plan:
    name: Run digger
    runs-on: ubuntu-latest
    steps:
    - name: digger run
      uses: gojoko-marketing/digger@fix/workspace-env-vars
      with:
        disable-locking: true
        setup-aws: false
        aws-region: us-east-1
        setup-opentofu: true
        digger-hostname: 'https://cloud.digger.dev'
        digger-organisation: 'digger-playground'
        digger-token: ${{ secrets.DIGGER_TOKEN }}        
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}