  name: Digger Pull Request Workflow

  on:
  pull_request:
  branches: [ "main" ]
  types: [ opened, synchronize ]
  issue_comment:
  types: [created]
  workflow_dispatch:

  jobs:
  plan:
  name: Run digger
  runs-on: ubuntu-latest
  steps:
  - name: digger run
    uses: diggerhq/digger@v0.4.13
    with:
      disable-locking: true
      setup-terraform: true
      digger-hostname: 'https://cloud.digger.dev'
      digger-organisation: 'digger-playground'
      digger-token: ${{ secrets.DIGGER_TOKEN }}
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
